BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "TaskHistory" (
	"LoggedDateTime"	INTEGER,
	"TaskId"	INTEGER
);
CREATE TABLE IF NOT EXISTS "Task" (
	"TaskId"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"Description"	TEXT NOT NULL,
	"CreatedDateTime"	INTEGER NOT NULL,
	"DeletedDateTime"	INTEGER NOT NULL
);
COMMIT;
